import { Inter } from "next/font/google";
import "../app/styles/home.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="header">
        <Link className="link-home" key="Home" href="/">Home</Link>
        </div>
        <div>{children}</div></body>
    </html>
  );
}
